sudo: false
language: node_js
cache:
  directories:
    - $HOME/.yarn-cache
node_js:
  - v6
before_install:
  - npm i -g yarn@^0.16.1
install:
  - yarn install
after_success:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
